version: "0.0.{build}"
package_version: $(appveyor_build_version)
image:
  - Ubuntu
configuration:
  - Release
artifacts:
  - path: publish/*.nupkg
platform: Any CPU
before_build:
  - dotnet tool restore
  - dotnet restore -v Minimal
build_script:
  - dotnet build
  - dotnet pack --no-build -o publish
test_script:
  - dotnet test
deploy:
  - provider: Environment
    name: Nuget v2
